import { assertCleanWorkingTree } from '../git/repo';
import { readManifest } from '../manifest/io';
import type { Registry } from '../registry/schema';
import { localKitOption, resolveRevision } from '../sources/resolveRevision';
import type { ApplyResult } from '../upgrade/apply';
import { applyUpgrade } from '../upgrade/apply';
import type { ActionType } from '../upgrade/plan';
import { planUpgrade, summarizePlan } from '../upgrade/plan';

export interface UpgradeOptions {
  projectRoot: string;
  registry: Registry;
  check: boolean;
  force: boolean;
  resolveLocalKit?: (revision: string) => string | undefined;
}

export interface UpgradeReport {
  fromRevision: string;
  toRevision: string;
  upToDate: boolean;
  summary: Record<ActionType, number>;
  moduleUpdates: Array<{ id: string; from: string; to: string }>;
  applied: ApplyResult | null;
  conflicted: string[];
  notes: string[];
}

const EMPTY_SUMMARY: Record<ActionType, number> = {
  skip: 0,
  add: 0,
  overwrite: 0,
  merge: 0,
  conflict: 0,
  delete: 0,
  orphan: 0,
};

export async function runUpgrade(options: UpgradeOptions): Promise<UpgradeReport> {
  const manifest = await readManifest(options.projectRoot);
  // Previewing is read-only, so it works on a dirty tree; applying does not.
  if (!options.check) {
    await assertCleanWorkingTree(options.projectRoot, { force: options.force });
  }

  // Where the registry's channel points today. Comparing the project against the
  // channel's name rather than its tip would report every project as current.
  const targetRevision = await resolveRevision({
    template: options.registry.kit.template,
    revision: options.registry.kit.revision,
    ...localKitOption(options.resolveLocalKit, options.registry.kit.revision),
  });

  if (manifest.kit.revision === targetRevision) {
    return {
      fromRevision: manifest.kit.revision,
      toRevision: targetRevision,
      upToDate: true,
      summary: EMPTY_SUMMARY,
      moduleUpdates: [],
      applied: null,
      conflicted: [],
      notes: ['Already on the latest kit revision.'],
    };
  }

  const plan = await planUpgrade({
    projectRoot: options.projectRoot,
    registry: options.registry,
    targetRevision,
    ...(options.resolveLocalKit === undefined ? {} : { resolveLocalKit: options.resolveLocalKit }),
  });

  try {
    const notes: string[] = [];
    if (plan.renderVersionChanged) {
      notes.push(
        'This project was generated by an older renderer; review the merge results closely.',
      );
    }
    for (const id of plan.droppedModuleIds) {
      notes.push(`Module "${id}" is no longer in the registry; its files were left untouched.`);
    }
    for (const id of plan.addedModuleIds) {
      notes.push(`Module "${id}" was installed because another module now requires it.`);
    }

    const report: UpgradeReport = {
      fromRevision: plan.fromRevision,
      toRevision: plan.toRevision,
      upToDate: false,
      summary: summarizePlan(plan),
      moduleUpdates: plan.moduleUpdates,
      applied: null,
      conflicted: plan.actions
        .filter((action) => action.type === 'conflict')
        .map((action) => action.path),
      notes,
    };

    if (options.check) return report;
    report.applied = await applyUpgrade(plan, options.registry);
    return report;
  } finally {
    await plan.cleanup();
  }
}
